FROM us-docker.pkg.dev/teknoir/gcr.io/compreface-core:latest-facenet
# Folder and file must match, and with the name added here: embedding-calculator/src/services/facescan/plugins/facenet/facenet.py
ADD facenet512_model.pb /app/ml/.models/facenet/calculator/facenet512/facenet512.pb